export enum PQRStatus {
  OPEN = 'OPEN',
  CATEGORIZED = 'CATEGORIZED',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING = 'WAITING',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  REOPENED = 'REOPENED',
  CANCELLED = 'CANCELLED',
}

export enum PQRNotificationTemplate {
  STATUS_CHANGE_ASSIGNED = 'STATUS_CHANGE_ASSIGNED',
  STATUS_CHANGE_IN_PROGRESS = 'STATUS_CHANGE_IN_PROGRESS',
  STATUS_CHANGE_RESOLVED = 'STATUS_CHANGE_RESOLVED',
  STATUS_CHANGE_CLOSED = 'STATUS_CHANGE_CLOSED',
  STATUS_CHANGE_REOPENED = 'STATUS_CHANGE_REOPENED',
  DEFAULT = 'DEFAULT',
}