export enum SecurityEventType {
  ACCESS_GRANTED = 'ACCESS_GRANTED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  PANIC_BUTTON = 'PANIC_BUTTON',
  CCTV_ALERT = 'CCTV_ALERT',
  ALARM_TRIGGERED = 'ALARM_TRIGGERED',
  OTHER = 'OTHER',
}
