export enum UserRole {
  ADMIN = 'ADMIN',
  COMPLEX_ADMIN = 'COMPLEX_ADMIN',
  RESIDENT = 'RESIDENT',
  STAFF = 'STAFF',
  APP_ADMIN = 'APP_ADMIN',
  RECEPTION = 'RECEPTION',
  SECURITY = 'SECURITY',
  CONCIERGE = 'CONCIERGE',
}
