'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useAuthStore } from '@/store/authStore';
import AdminHeader from '@/components/admin/layout/AdminHeader';
import AdminSidebar from '@/components/admin/layout/AdminSidebar';
import { Loader2, DollarSign, Activity, Calendar, MessageSquare } from 'lucide-react';
import Link from 'next/link';
export default function ReportsPage() {
    const { user, loading: authLoading, logout } = useAuthStore();
    const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
    if (authLoading) {
        return (_jsx("div", { className: "min-h-screen flex items-center justify-center", children: _jsx(Loader2, { className: "h-8 w-8 animate-spin" }) }));
    }
    if (!user || (user.role !== 'ADMIN' && user.role !== 'COMPLEX_ADMIN')) {
        return (_jsx("div", { className: "min-h-screen flex items-center justify-center", children: _jsxs("div", { className: "text-center", children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900 mb-2", children: "Acceso Denegado" }), _jsx("p", { className: "text-gray-600", children: "No tienes permisos para acceder a esta p\u00E1gina." })] }) }));
    }
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx(AdminHeader, { adminName: (user === null || user === void 0 ? void 0 : user.name) || "Administrador", complexName: "Conjunto Residencial Armon\u00EDa", onLogout: logout }), _jsxs("div", { className: "flex", children: [_jsx(AdminSidebar, { collapsed: sidebarCollapsed, onToggle: () => setSidebarCollapsed(!sidebarCollapsed) }), _jsx("main", { className: `flex-1 transition-all duration-300 ${sidebarCollapsed ? 'ml-16' : 'ml-64'} mt-16 p-6`, children: _jsxs("div", { className: "max-w-7xl mx-auto", children: [_jsxs("div", { className: "mb-6", children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900", children: "Generaci\u00F3n de Reportes" }), _jsx("p", { className: "text-gray-600 mt-2", children: "Selecciona el tipo de reporte que deseas generar." })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: [_jsxs(Link, { href: "/admin/reports/financial", className: "bg-white rounded-lg shadow p-6 hover:shadow-lg transition-shadow cursor-pointer flex flex-col items-center text-center", children: [_jsx(DollarSign, { className: "h-12 w-12 text-green-600 mb-4" }), _jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2", children: "Reportes Financieros" }), _jsx("p", { className: "text-gray-600 text-sm", children: "Genera reportes de ingresos, egresos, presupuestos y m\u00E1s." })] }), _jsxs(Link, { href: "/admin/reports/activity", className: "bg-white rounded-lg shadow p-6 hover:shadow-lg transition-shadow cursor-pointer flex flex-col items-center text-center", children: [_jsx(Activity, { className: "h-12 w-12 text-blue-600 mb-4" }), _jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2", children: "Reportes de Actividad" }), _jsx("p", { className: "text-gray-600 text-sm", children: "Visualiza la actividad de usuarios y del sistema." })] }), _jsxs(Link, { href: "/admin/reports/service-usage", className: "bg-white rounded-lg shadow p-6 hover:shadow-lg transition-shadow cursor-pointer flex flex-col items-center text-center", children: [_jsx(Calendar, { className: "h-12 w-12 text-purple-600 mb-4" }), _jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2", children: "Reportes de Uso de Servicios" }), _jsx("p", { className: "text-gray-600 text-sm", children: "Analiza la ocupaci\u00F3n de \u00E1reas comunes y servicios." })] }), _jsxs(Link, { href: "/admin/reports/pqr", className: "bg-white rounded-lg shadow p-6 hover:shadow-lg transition-shadow cursor-pointer flex flex-col items-center text-center", children: [_jsx(MessageSquare, { className: "h-12 w-12 text-orange-600 mb-4" }), _jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2", children: "Reportes de PQR" }), _jsx("p", { className: "text-gray-600 text-sm", children: "Obt\u00E9n m\u00E9tricas sobre peticiones, quejas y reclamos." })] })] })] }) })] })] }));
}
